// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: apis/dealer.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_apis_dealer_proto protoreflect.FileDescriptor

var file_apis_dealer_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x38, 0x0a, 0x06, 0x44, 0x65, 0x61, 0x6c, 0x65,
	0x72, 0x12, 0x2e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x0f, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x74, 0x67, 0x61, 0x6e, 0x65, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x64, 0x2f, 0x61, 0x70,
	0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_apis_dealer_proto_goTypes = []interface{}{
	(*GetDealRequest)(nil), // 0: GetDealRequest
	(*GetDealStream)(nil),  // 1: GetDealStream
}
var file_apis_dealer_proto_depIdxs = []int32{
	0, // 0: Dealer.GetDeal:input_type -> GetDealRequest
	1, // 1: Dealer.GetDeal:output_type -> GetDealStream
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apis_dealer_proto_init() }
func file_apis_dealer_proto_init() {
	if File_apis_dealer_proto != nil {
		return
	}
	file_apis_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apis_dealer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_dealer_proto_goTypes,
		DependencyIndexes: file_apis_dealer_proto_depIdxs,
	}.Build()
	File_apis_dealer_proto = out.File
	file_apis_dealer_proto_rawDesc = nil
	file_apis_dealer_proto_goTypes = nil
	file_apis_dealer_proto_depIdxs = nil
}
